export { VERSION } from './version.js'
export * from './types.js'
export * as AST from './ast.js'
export type { GlobalOptions, OptionalTreatment, SchemaOptions } from './options.js'
export type { GlobalConfig, SchemaConfig } from './config.js'
export { configure, defaults, getConfig } from './config.js'
export { equals as deepEquals } from './equals.js'
export { has } from './has.js'
export { parseArgs } from './parseArgs.js'
export { t } from './schema.js'
