packages:
  - examples/*/
  - bin
  - packages/*/
catalog:
  '@ark/attest': ^0.44.8
  '@babel/cli': ^7.25.9
  '@babel/core': ^7.26.0
  '@babel/plugin-transform-export-namespace-from': ^7.25.9
  '@babel/plugin-transform-modules-commonjs': ^7.25.9
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.9
  '@fast-check/vitest': ^0.2.2
  '@types/node': ^22.9.0
  '@prettier/sync': ^0.5.2
  '@types/madge': ^5.0.3
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  babel-plugin-annotate-pure-calls: ^0.4.0
  fast-check: ^4.1.1
  madge: ^8.0.0
  tinybench: ^3.0.4
  typescript: 5.8.3
  vitest: 3.2.4

  '@sinclair/typebox': ^0.34.38
  arktype: ^2.1.20
  valibot: 1.1.0
  zod: ^4.0.14
  '@types/lodash.isequal': ^4.5.8
  'lodash.isequal': ^4.5.0
