packages:
  - examples/*/
  - bin
  - packages/*/
catalog:
  '@ark/attest': ^0.44.8
  '@babel/cli': ^7.25.9
  '@babel/core': ^7.26.0
  '@babel/plugin-transform-export-namespace-from': ^7.25.9
  '@babel/plugin-transform-modules-commonjs': ^7.25.9
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.9
  '@fast-check/vitest': ^0.2.1
  '@types/node': ^22.9.0
  '@types/madge': ^5.0.3
  '@vitest/coverage-v8': 3.1.1
  '@vitest/ui': 3.1.1
  'zod4': 'npm:zod@4.0.0-beta.20250424T163858'
  'zod3': 'npm:zod@3'
  babel-plugin-annotate-pure-calls: ^0.4.0
  fast-check: ^4.1.1
  typescript: 5.8.2
  vitest: ^3.0.4
  madge: ^8.0.0
  tinybench: ^3.0.4
