packages:
  - examples/*/
  - bin
  - packages/*/

catalog:
  '@ark/attest': ^0.44.8
  '@babel/cli': ^7.25.9
  '@babel/core': ^7.26.0
  '@babel/plugin-transform-export-namespace-from': ^7.25.9
  '@babel/plugin-transform-modules-commonjs': ^7.25.9
  '@changesets/changelog-github': ^0.5.0
  '@changesets/cli': ^2.27.9
  '@prettier/sync': 0.5.5
  'typebox': 1.0.0
  '@types/lodash.isequal': ^4.5.8
  '@types/madge': ^5.0.3
  '@types/node': ^22.9.0
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  arktype: 2.1.20
  babel-plugin-annotate-pure-calls: ^0.4.0
  fast-check: ^4.1.1
  lodash.isequal: ^4.5.0
  madge: ^8.0.0
  tinybench: ^3.0.4
  typescript: 5.9.2
  valibot: 1.1.0
  vitest: 3.2.4
  zod: 4.1.3
