export type {
  LowerBound as t_LowerBound,
  Free as t_Free,
  F as t_F,
  Fixpoint as t_Fixpoint,
} from './schema.js'
export {
  never as t_never,
  unknown as t_unknown,
  void as t_void,
  any as t_any,
  null as t_null,
  undefined as t_undefined,
  symbol as t_symbol,
  boolean as t_boolean,
  integer as t_integer,
  bigint as t_bigint,
  number as t_number,
  string as t_string,
  eq as t_eq,
  optional as t_optional,
  array as t_array,
  record as t_record,
  object as t_object,
  tuple as t_tuple,
  union as t_union,
  intersect as t_intersect,
  of as t_of,
} from './schema.js'
import * as t from './schema.js'

export const def = {
  never: t.never.def,
  unknown: t.unknown.def,
  void: t.void.def,
  any: t.any.def,
  null: t.null.def,
  undefined: t.undefined.def,
  symbol: t.symbol.def,
  boolean: t.boolean.def,
  integer: t.integer.def,
  bigint: t.bigint.def,
  number: t.number.def,
  string: t.string.def,
  eq: t.eq.def,
  optional: t.optional.def,
  array: t.array.def,
  record: t.record.def,
  union: t.union.def,
  intersect: t.intersect.def,
  object: t.object.def,
  tuple: t.tuple.def,
};
